### ISSUE TITLE
uninitialized constant CalendarDateSelect

### ISSUE THREAD

**Issue by iamladi** [jamis/bucketwise#11]
I've tried to run the application on my local computer, but I'm receiving message: "uninitialized constant CalendarDateSelect". Didn't have time to investigate. Maybe you know how to fix this very quickly. Thanks

**Comment by jamis** [comment]
It works fine for me. Did you follow the setup instructions in the README?

**Comment by iamladi** [comment]
You're absolutely right! Sorry my big FAIL! Please delete this issue. Once again sorry!

**Comment by jamis** [comment]
No worries! Glad it was easy to "fix". :)
