### ISSUE TITLE
Missing success16.png

### ISSUE THREAD

**Issue by KieranP** [jamis/bucketwise#13]
Processing EventsController#create (for 127.0.0.1 at 2009-05-16 11:08:29) [POST]

[snip]

Processing ApplicationController#index (for 127.0.0.1 at 2009-05-16 11:08:30) [GET]

ActionController::RoutingError (No route matches "/images/success16.png" with {:method=>:get}):

Rendering rescues/layout (not_found)

**Comment by jamis** [comment]
Fixed in e951d578cbbd1e9efc011504dd0570a59d677dd3. Sorry that took so long. ;)
