### ISSUE TITLE
Floating point error in ending balance during reconciliation

### ISSUE THREAD

**Issue by sofal** [jamis/bucketwise#17]
In app/models/statement.rb:17 the call to to_i can result in a strange rounding error as demonstrated in IRB:

```
$ irb
>> (2557.68 * 100).to_i
=> 255767
```

This can mean that for a particular statement, reconciliation is never quite possible.

**Comment by cmaggard** [comment]
Fixed in cmaggard/bucketwise@9eb4d7aedd35328cfa647dbb0c6b47c1601e023c

**Comment by jamis** [comment]
Awesome! Thanks for this fix. I've merged it in.
