### ISSUE TITLE
Error running cap local externals:setup - 'Readme.txt' would be overwritten by merge

### ISSUE THREAD

**Issue by jjolma** [jamis/bucketwise#19]
$ cap local externals:setup

<pre>
  * executing `local'
  * executing `externals:setup'
configuring vendor/plugins/haml
remote: Counting objects: 12496, done.
remote: Compressing objects: 100% (4100/4100), done.
remote: Total 12496 (delta 8371), reused 12235 (delta 8111)
configuring vendor/rails
remote: Counting objects: 106035, done.
remote: Compressing objects: 100% (23766/23766), done.
remote: Total 106035 (delta 82025), reused 104753 (delta 81038)
configuring vendor/plugins/calendar_date_select
remote: Counting objects: 1332, done.
remote: Compressing objects: 100% (640/640), done.
remote: Total 1332 (delta 772), reused 973 (delta 570)
error: Untracked working tree file 'Readme.txt' would be overwritten by merge.
vendor/plugins/cached_externals/recipes/cached_externals.rb:54:in `load': Error checking out 88b7caf7acecf31186661c0efd6bc606cdcc666d to /Users/jolma/depot/shared/externals/vendor/plugins/calendar_date_select/88b7caf7acecf31186661c0efd6bc606cdcc666d (RuntimeError)
    from vendor/plugins/cached_externals/recipes/cached_externals.rb:41:in `each'
    from vendor/plugins/cached_externals/recipes/cached_externals.rb:41:in `load'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/lib/capistrano/configuration/execution.rb:128:in `instance_eval'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/lib/capistrano/configuration/execution.rb:128:in `invoke_task_directly_without_callbacks'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/lib/capistrano/configuration/execution.rb:81:in `execute_task'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/lib/capistrano/configuration/execution.rb:93:in `find_and_execute_task'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions_without_help'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/lib/capistrano/cli/execute.rb:44:in `each'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/lib/capistrano/cli/execute.rb:44:in `execute_requested_actions_without_help'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/lib/capistrano/cli/help.rb:19:in `execute_requested_actions'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/lib/capistrano/cli/execute.rb:33:in `execute!'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/lib/capistrano/cli/execute.rb:14:in `execute'
    from /Users/jolma/.gem/ruby/1.8/gems/capistrano-2.5.5/bin/cap:4
    from /usr/bin/cap:19:in `load'
    from /usr/bin/cap:19
</pre>

$ rails --version

Rails 2.3.2

$ ruby --version

ruby 1.8.7 (2008-08-11 patchlevel 72) [i686-darwin9.6.0]

$ git --version

git version 1.5.5.1

$ cap --version

Capistrano v2.5.5

$ git log

<pre>
commit 379777136d2f50563b2242439b640d881754b3cf
Author: Jamis Buck <jamis@37signals.com>
Date:   Mon May 25 22:04:55 2009 -0600

    update changelog
</pre>

**Comment by marcric** [comment]
I get another "cap local externals:setup" error:

E:\TEMP\bucketwise>cap local externals:setup
- executing `local'
- executing `externals:setup'
  configuring vendor/plugins/haml
  The system cannot find the path specified.
  vendor/plugins/cached_externals/recipes/cached_externals.rb:54:in`load': Error
  checking out a4f0471c5be4640029f6deaca5d6ded45e15725c to E:/TEMP/shared/externals/vendor/plugins/haml/a4f0471c5be4640029f6deaca5d6ded45e15725c (RuntimeError)
      from vendor/plugins/cached_externals/recipes/cached_externals.rb:41:in `each'
      from vendor/plugins/cached_externals/recipes/cached_externals.rb:41:in`load'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/configuration/execution.rb:139:in `instance_eval'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/configuration/execution.rb:139:in`invoke_task_directly_without_callbacks'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/configuration/execution.rb:89:in`execute_task'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/cli/execute.rb:45:in`execute_requested_actions_without_help'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/cli/execute.rb:44:in `each'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/cli/execute.rb:44:in`execute_requested_actions_without_help'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/cli/help.rb:19:in `execute_requested_actions'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/cli/execute.rb:33:in`execute!'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/lib/capistrano/cli/execute.rb:14:in `execute'
      from d:/Ruby/lib/ruby/gems/1.8/gems/capistrano-2.5.9/bin/cap:4
      from d:/Ruby/bin/cap:19:in`load'
      from d:/Ruby/bin/cap:19

E:\TEMP\bucketwise>

**Comment by jamis** [comment]
Note that the cached-externals stuff will not work on Windows due to its use of symlinks. So, if you want to set up Bucketwise on windows, you have to clone all the external dependencies manually.
