### ISSUE TITLE
Unable to resolve revision for '2.0.9' on repository 'git://github.com/nex3/haml.git'

### ISSUE THREAD

**Issue by chabgood** [jamis/bucketwise#22]
Howdy.  I ran the "ap local externals:setup"  and it cannot seem to locate the revision in the file.  I tried several diferent one but to no avail.

**Comment by jamis** [comment]
That's...odd. The revision is right here: http://github.com/nex3/haml/tree/2.0.9. No idea why you might be having trouble with it, but it's really not Bucketwise's issue.
