### ISSUE TITLE
Show all 6 buckets shows up when only 5 are visible

### ISSUE THREAD

**Issue by watkyn** [jamis/bucketwise#9]
It looks like the "See all 6 buckets" link shows up on the bottom of my account but I only have 5 buckets when I click on "See all 6 buckets"

It looks like the Aside bucket is included in the count but it is not visible until it is used for the first time?

**Comment by jamis** [comment]
I _think_ this might be as simple to fix as dup'ing the result of [this #to_a call](http://github.com/jamis/bucketwise/blob/4d2ffbb87eb73a514902df7276cd1f6da5a0dc18/app/models/account.rb#L32). I'll investigate when I have a chance.

**Comment by watkyn** [comment]
That makes sense.  I tried it out and wrote a test to verify that the with_defaults buckets can be modified without affecting the "real" buckets.  Thanks for the tip.

**Comment by jamis** [comment]
Awesome. I cherry-picked your commit into 10de90fd6dd1b66b4977cd33c24a9ee3d6af9238. Thanks for getting that fixed!
